
from email.message import EmailMessage
import smtplib
import ssl


sender = "faheempa788@gmail.com"
reciver = "rasheednazanmail@gmail.com"
password = "vwdjnmyftnoxocsd" # password generated by google for python
subject = "hey bruh...this is a test :)"
body = "this mail is sent using python.."

message = """From: faheem {sender}
To: ali {reciver}
Subject: {subject} \n
{body}
"""

em = EmailMessage()
em['From']=sender
em['To']=reciver
em['Subject']=subject
em.set_content(body)

context = ssl.create_default_context()
# for extra security

with smtplib.SMTP_SSL("smtp.gmail.com",465, context=context) as smtp:
    smtp.login(sender,password)
    print("Logged in")

    smtp.sendmail(sender, reciver, em.as_string())
    print("mail is sent")







